CUSTOM_BUILD_TYPE ?= UNOFFICIAL

# MorbiOs Props
MORBIOS_BASE_VERSION = Alpha

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)

# Platform (Android Version)
CUSTOM_PLATFORM_VERSION := 13.0

CUSTOM_VERSION := MOrbiOs_$(MORBIOS_BASE_VERSION)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := thirteen