CUSTOM_BUILD_TYPE ?= UNOFFICIAL

MORBIOS_BASE_VERSION := Experimental

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)

CUSTOM_PLATFORM_VERSION := 13.0
MORBIOS_BUILD_VERSION := 13.0

CUSTOM_VERSION := MORBIOS-$(CUSTOM_PLATFORM_VERSION)-$(MORBIOS_BASE_VERSION)-$(CUSTOM_BUILD)-$(CUSTOM_BUILD_TYPE)-$(CUSTOM_BUILD_DATE)
CUSTOM_VERSION_PROP := thirteen
